#ifndef GPU_SENTRY_CONFIG_H
#define GPU_SENTRY_CONFIG_H

#define GPU_SENTRY_DEFAULT_SERVER_ADDR "127.0.0.1:59400"
#define GPU_SENTRY_DEFAULT_RING_CAPACITY 4096u
#define GPU_SENTRY_DEFAULT_DRAIN_BATCH_SIZE 128u
#define GPU_SENTRY_DEFAULT_RECONNECT_BACKOFF_MS 1000u
#define GPU_SENTRY_DISABLE_ENV "GPU_SENTRY_DISABLE"
#define GPU_SENTRY_HOOK_VERSION "0.1.0"

#endif  // GPU_SENTRY_CONFIG_H
